import type { AnimationPattern, AnimationPatternDefinition } from "./types";

/**
 * Complete metadata for all 56 animation patterns.
 */
export const ANIMATION_PATTERNS: Record<
  AnimationPattern,
  AnimationPatternDefinition
> = {
  "horizontal-wave": {
    key: "horizontal-wave",
    nameJa: "横波(上→下)",
    nameEn: "Horizontal Wave",
    description: "Wave propagates from top to bottom row by row",
    category: "wave",
  },
  "horizontal-wave-reverse": {
    key: "horizontal-wave-reverse",
    nameJa: "横波(下→上)",
    nameEn: "Horizontal Wave Reverse",
    description: "Wave propagates from bottom to top row by row",
    category: "wave",
  },
  "vertical-wave": {
    key: "vertical-wave",
    nameJa: "縦波(左→右)",
    nameEn: "Vertical Wave",
    description: "Wave propagates from left to right column by column",
    category: "wave",
  },
  "vertical-wave-reverse": {
    key: "vertical-wave-reverse",
    nameJa: "縦波(右→左)",
    nameEn: "Vertical Wave Reverse",
    description: "Wave propagates from right to left column by column",
    category: "wave",
  },
  "zigzag-horizontal": {
    key: "zigzag-horizontal",
    nameJa: "ジグザグ(横)",
    nameEn: "Zigzag Horizontal",
    description: "Zigzag pattern moving horizontally",
    category: "wave",
  },
  "zigzag-vertical": {
    key: "zigzag-vertical",
    nameJa: "ジグザグ(縦)",
    nameEn: "Zigzag Vertical",
    description: "Zigzag pattern moving vertically",
    category: "wave",
  },
  "bounce-horizontal": {
    key: "bounce-horizontal",
    nameJa: "バウンス(横)",
    nameEn: "Bounce Horizontal",
    description: "Wave bounces back horizontally",
    category: "wave",
  },
  "bounce-vertical": {
    key: "bounce-vertical",
    nameJa: "バウンス(縦)",
    nameEn: "Bounce Vertical",
    description: "Wave bounces back vertically",
    category: "wave",
  },
  "diagonal-forward": {
    key: "diagonal-forward",
    nameJa: "対角線(左上→右下)",
    nameEn: "Diagonal Forward",
    description: "Wave propagates diagonally from top-left to bottom-right",
    category: "diagonal",
  },
  "diagonal-backward": {
    key: "diagonal-backward",
    nameJa: "対角線(右下→左上)",
    nameEn: "Diagonal Backward",
    description: "Wave propagates diagonally from bottom-right to top-left",
    category: "diagonal",
  },
  "diagonal-reverse": {
    key: "diagonal-reverse",
    nameJa: "逆対角線(右上→左下)",
    nameEn: "Diagonal Reverse",
    description: "Wave propagates diagonally from top-right to bottom-left",
    category: "diagonal",
  },
  "diagonal-reverse-backward": {
    key: "diagonal-reverse-backward",
    nameJa: "逆対角線(左下→右上)",
    nameEn: "Diagonal Reverse Backward",
    description: "Wave propagates diagonally from bottom-left to top-right",
    category: "diagonal",
  },
  "center-outward": {
    key: "center-outward",
    nameJa: "中心から外側へ",
    nameEn: "Center Outward",
    description: "Expands from center to the edges",
    category: "center",
  },
  "center-inward": {
    key: "center-inward",
    nameJa: "外側から中心へ",
    nameEn: "Center Inward",
    description: "Contracts from the edges to center",
    category: "center",
  },
  "spiral-clockwise": {
    key: "spiral-clockwise",
    nameJa: "らせん(時計回り)",
    nameEn: "Spiral Clockwise",
    description: "Spirals clockwise from the outside edge",
    category: "center",
  },
  "spiral-counterclockwise": {
    key: "spiral-counterclockwise",
    nameJa: "らせん(反時計回り)",
    nameEn: "Spiral Counterclockwise",
    description: "Spirals counterclockwise from the outside edge",
    category: "center",
  },
  "corner-top-left": {
    key: "corner-top-left",
    nameJa: "左上コーナー",
    nameEn: "Top-Left Corner",
    description: "Expands from top-left corner",
    category: "corner",
  },
  "corner-top-right": {
    key: "corner-top-right",
    nameJa: "右上コーナー",
    nameEn: "Top-Right Corner",
    description: "Expands from top-right corner",
    category: "corner",
  },
  "corner-bottom-left": {
    key: "corner-bottom-left",
    nameJa: "左下コーナー",
    nameEn: "Bottom-Left Corner",
    description: "Expands from bottom-left corner",
    category: "corner",
  },
  "corner-bottom-right": {
    key: "corner-bottom-right",
    nameJa: "右下コーナー",
    nameEn: "Bottom-Right Corner",
    description: "Expands from bottom-right corner",
    category: "corner",
  },
  "corners-inward": {
    key: "corners-inward",
    nameJa: "四隅から中心へ",
    nameEn: "Four Corners Inward",
    description: "All four corners simultaneously converge to center",
    category: "corner",
  },
  "rotate-clockwise": {
    key: "rotate-clockwise",
    nameJa: "回転(時計回り)",
    nameEn: "Rotate Clockwise",
    description: "Rotates around the grid clockwise from top",
    category: "rotation",
  },
  "rotate-counterclockwise": {
    key: "rotate-counterclockwise",
    nameJa: "回転(反時計回り)",
    nameEn: "Rotate Counterclockwise",
    description: "Rotates around the grid counterclockwise from top",
    category: "rotation",
  },
  "cross-rotate": {
    key: "cross-rotate",
    nameJa: "十字回転",
    nameEn: "Cross Rotate",
    description: "Cross pattern rotates, corners hidden",
    category: "rotation",
  },
  pinwheel: {
    key: "pinwheel",
    nameJa: "風車",
    nameEn: "Pinwheel",
    description: "Pinwheel pattern from center outward",
    category: "rotation",
  },
  "checkerboard-a": {
    key: "checkerboard-a",
    nameJa: "市松模様A",
    nameEn: "Checkerboard A",
    description: "Alternates between white and black squares pattern A",
    category: "complex",
  },
  "checkerboard-b": {
    key: "checkerboard-b",
    nameJa: "市松模様B",
    nameEn: "Checkerboard B",
    description:
      "Alternates between white and black squares pattern B (inverted)",
    category: "complex",
  },
  "alternating-rows": {
    key: "alternating-rows",
    nameJa: "行交互",
    nameEn: "Alternating Rows",
    description: "Rows alternate blinking",
    category: "complex",
  },
  "alternating-columns": {
    key: "alternating-columns",
    nameJa: "列交互",
    nameEn: "Alternating Columns",
    description: "Columns alternate blinking",
    category: "complex",
  },
  "x-pattern": {
    key: "x-pattern",
    nameJa: "X字",
    nameEn: "X Pattern",
    description: "Forms an X shape from corners to center",
    category: "complex",
  },
  "plus-pattern": {
    key: "plus-pattern",
    nameJa: "プラス字",
    nameEn: "Plus Pattern",
    description: "Forms a + shape animating outward from center",
    category: "complex",
  },
  "single-row": {
    key: "single-row",
    nameJa: "一列点滅(中央行)",
    nameEn: "Single Row",
    description: "Only the center row blinks",
    category: "special",
  },
  "single-column": {
    key: "single-column",
    nameJa: "一列点滅(中央列)",
    nameEn: "Single Column",
    description: "Only the center column blinks",
    category: "special",
  },
  "cross-expand": {
    key: "cross-expand",
    nameJa: "十字展開",
    nameEn: "Cross Expand",
    description: "Expands in a cross pattern from the center",
    category: "special",
  },
  random: {
    key: "random",
    nameJa: "ランダム",
    nameEn: "Random",
    description: "Blinks in a random sequence",
    category: "special",
  },
  "single-dot-center": {
    key: "single-dot-center",
    nameJa: "中心点のみ",
    nameEn: "Single Dot Center",
    description: "Only the center dot pulses",
    category: "minimal",
  },
  "top-row": {
    key: "top-row",
    nameJa: "上行のみ",
    nameEn: "Top Row",
    description: "Only the top row animates left to right",
    category: "minimal",
  },
  "bottom-row": {
    key: "bottom-row",
    nameJa: "下行のみ",
    nameEn: "Bottom Row",
    description: "Only the bottom row animates left to right",
    category: "minimal",
  },
  "left-column": {
    key: "left-column",
    nameJa: "左列のみ",
    nameEn: "Left Column",
    description: "Only the left column animates top to bottom",
    category: "minimal",
  },
  "right-column": {
    key: "right-column",
    nameJa: "右列のみ",
    nameEn: "Right Column",
    description: "Only the right column animates top to bottom",
    category: "minimal",
  },
  "opposite-corners-a": {
    key: "opposite-corners-a",
    nameJa: "対角コーナーA",
    nameEn: "Opposite Corners A",
    description: "Top-left and bottom-right corners alternate",
    category: "minimal",
  },
  "opposite-corners-b": {
    key: "opposite-corners-b",
    nameJa: "対角コーナーB",
    nameEn: "Opposite Corners B",
    description: "Top-right and bottom-left corners alternate",
    category: "minimal",
  },
  "four-corners-only": {
    key: "four-corners-only",
    nameJa: "四隅のみ",
    nameEn: "Four Corners Only",
    description: "Only the four corner dots light in sequence",
    category: "edge",
  },
  "frame-wave": {
    key: "frame-wave",
    nameJa: "外周波",
    nameEn: "Frame Wave",
    description: "Outer frame wave pattern",
    category: "edge",
  },
  "frame-bounce": {
    key: "frame-bounce",
    nameJa: "外周バウンス",
    nameEn: "Frame Bounce",
    description: "Frame dots bounce back and forth",
    category: "edge",
  },
  "edges-only": {
    key: "edges-only",
    nameJa: "辺中心のみ",
    nameEn: "Edges Only",
    description: "Only the middle dots of each edge",
    category: "edge",
  },
  "quad-top-left": {
    key: "quad-top-left",
    nameJa: "左上クアッド",
    nameEn: "Top-Left Quad",
    description: "Top-left 2×2 area animates",
    category: "quad",
  },
  "quad-top-right": {
    key: "quad-top-right",
    nameJa: "右上クアッド",
    nameEn: "Top-Right Quad",
    description: "Top-right 2×2 area animates",
    category: "quad",
  },
  "quad-bottom-left": {
    key: "quad-bottom-left",
    nameJa: "左下クアッド",
    nameEn: "Bottom-Left Quad",
    description: "Bottom-left 2×2 area animates",
    category: "quad",
  },
  "quad-bottom-right": {
    key: "quad-bottom-right",
    nameJa: "右下クアッド",
    nameEn: "Bottom-Right Quad",
    description: "Bottom-right 2×2 area animates",
    category: "quad",
  },
  "l-shape-tl": {
    key: "l-shape-tl",
    nameJa: "L字左上",
    nameEn: "L-Shape Top-Left",
    description: "L-shape in top-left (top row + left column)",
    category: "shape",
  },
  "l-shape-tr": {
    key: "l-shape-tr",
    nameJa: "L字右上",
    nameEn: "L-Shape Top-Right",
    description: "L-shape in top-right (top row + right column)",
    category: "shape",
  },
  "l-shape-bl": {
    key: "l-shape-bl",
    nameJa: "L字左下",
    nameEn: "L-Shape Bottom-Left",
    description: "L-shape in bottom-left (bottom row + left column)",
    category: "shape",
  },
  "l-shape-br": {
    key: "l-shape-br",
    nameJa: "L字右下",
    nameEn: "L-Shape Bottom-Right",
    description: "L-shape in bottom-right (bottom row + right column)",
    category: "shape",
  },
  "t-shape-horizontal": {
    key: "t-shape-horizontal",
    nameJa: "T字横",
    nameEn: "T-Shape Horizontal",
    description: "T-shape (top row + center column)",
    category: "shape",
  },
  "t-shape-vertical": {
    key: "t-shape-vertical",
    nameJa: "T字縦",
    nameEn: "T-Shape Vertical",
    description: "Rotated T (left column + center row)",
    category: "shape",
  },
};

/**
 * Pattern categories with Japanese labels and pattern lists.
 * Use this to display patterns grouped by type.
 */
export const PATTERN_CATEGORIES = {
  wave: {
    label: "波系",
    patterns: [
      "horizontal-wave",
      "horizontal-wave-reverse",
      "vertical-wave",
      "vertical-wave-reverse",
      "zigzag-horizontal",
      "zigzag-vertical",
      "bounce-horizontal",
      "bounce-vertical",
    ] as const,
  },
  diagonal: {
    label: "対角線系",
    patterns: [
      "diagonal-forward",
      "diagonal-backward",
      "diagonal-reverse",
      "diagonal-reverse-backward",
    ] as const,
  },
  center: {
    label: "中心系",
    patterns: [
      "center-outward",
      "center-inward",
      "spiral-clockwise",
      "spiral-counterclockwise",
    ] as const,
  },
  corner: {
    label: "コーナー系",
    patterns: [
      "corner-top-left",
      "corner-top-right",
      "corner-bottom-left",
      "corner-bottom-right",
      "corners-inward",
    ] as const,
  },
  rotation: {
    label: "回転系",
    patterns: [
      "rotate-clockwise",
      "rotate-counterclockwise",
      "cross-rotate",
      "pinwheel",
    ] as const,
  },
  complex: {
    label: "複雑系",
    patterns: [
      "checkerboard-a",
      "checkerboard-b",
      "alternating-rows",
      "alternating-columns",
      "x-pattern",
      "plus-pattern",
    ] as const,
  },
  special: {
    label: "特殊",
    patterns: [
      "single-row",
      "single-column",
      "cross-expand",
      "random",
    ] as const,
  },
  minimal: {
    label: "ミニマル",
    patterns: [
      "single-dot-center",
      "top-row",
      "bottom-row",
      "left-column",
      "right-column",
      "opposite-corners-a",
      "opposite-corners-b",
    ] as const,
  },
  edge: {
    label: "エッジ系",
    patterns: [
      "four-corners-only",
      "frame-wave",
      "frame-bounce",
      "edges-only",
    ] as const,
  },
  quad: {
    label: "クアッド系",
    patterns: [
      "quad-top-left",
      "quad-top-right",
      "quad-bottom-left",
      "quad-bottom-right",
    ] as const,
  },
  shape: {
    label: "形状系",
    patterns: [
      "l-shape-tl",
      "l-shape-tr",
      "l-shape-bl",
      "l-shape-br",
      "t-shape-horizontal",
      "t-shape-vertical",
    ] as const,
  },
};
